services:
  backend:
    build:
      context: ./backend
    container_name: em-backend
    expose:
      - "8080"
    networks:
      - em-net

    # Проверка
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8080/', timeout=2).read()"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s


    #Лимиты
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 125M

    #Автозапуск
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: em-nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - em-net

    # Проверка
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

    #Лимиты
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M

    # Автозапуск
    restart: unless-stopped


networks:
  em-net:
    driver: bridge
